### ISSUE TITLE
File Tab Context Option to Move Tab to Module Group

### ISSUE THREAD

**Issue by pcpro178** [sliptrixx/cpp-group#4]
A file tab context menu option is needed to move the respective file tab, so that it is next to the other file in its module group.  The following screen grab show a file tab context menu and suggested placement for the new context menu option.

![image](https://github.com/user-attachments/assets/7487c94c-f784-43ca-b8f6-f5fa168bf320)

**Comment by sliptrixx** [comment]
I spent some time researching and the VSCode tabs API appears to be not mature enough for me to implement this feature. I currently use `MoveActiveEditor` command to "hack" the main implementation because when you open a unopened file, it's opened in the current editor.

If things change with VSCode or if someone have better insight into it's underlying functionality, please do share. But as of right now, this requested feature cannot be implemented.

**Comment by pcpro178** [comment]
What about, on move request, close the file and reopen it next to its
counterpart?

**Comment by sliptrixx** [comment]
That is one possible solution but I'm hesitant about it because of all the unintended consequences. A good example could be intellisense having to reload the file or source control marking a file for edit. There are also many other edge cases like the file having unsaved edits and such. 

At the end of the day it's a move tab operation and the extension springing unexpected behavior onto the users is not a good practice. I think the best course of action is to table this feature and revisit this once VSCode has added the required API.
